### ISSUE TITLE
What about installing the PHP local mirror package?

### ISSUE THREAD

**Issue by pgy866** [phpenv/phpenv#111]
Is it possible to specify "/cache" like PYENV does,

What about installing the PHP local mirror package?

**Comment by debo** [comment]
Unfortunately this is a feature that should be implemented in php-build and not phpenv. With that said, sadly, I have bad news because the php-build team already said they won't implement it because there is not enough interest. You can find the conversation [here](https://github.com/php-build/php-build/issues/476).

**Comment by pgy866** [comment]
Thanks a lot, I think this would be great if supported for local development PHP testing.

I made it happen in my own way
Refer to it for those who need it
Thanks a lot, I think this would be great if supported for local development PHP testing.

I made it happen in my own way
Refer to it for those who need it.


- And with the git feature, we can update and switch versions of php without tags at any time

```
git clone https://github.com/php/php-src.git ~/php-8.1.3

cd ~/php-8.1.3

git tag

sudo git checkout php-8.1.3

tar --exclude .git --exclude .github -cjvf ~/php-8.1.3.tar.bz2 -C ~/php-8.1.3 ../php-8.1.3

cp -r (phpenv root)/plugins/php-build/share/php-build/definitions/8.1.3 (phpenv root)/plugins/php-build/share/php-build/definitions/L8.1.3

```
- Open for editing
```
deepin-editor (phpenv root)/plugins/php-build/share/php-build/definitions/L8.1.3
```

- change into（save close）

```
configure_option "--enable-gd"
configure_option "--with-jpeg"
configure_option "--with-zip"
configure_option "--with-mhash"

configure_option -D "--with-xmlrpc"

install_package "~/php-8.1.3.tar.bz2"
install_xdebug "3.1.3"
enable_builtin_opcache

```
- install
```
phpenv install L8.1.3
```
```
(phpenv root)/versions/L8.1.3
```
> `(phpenv root)` is the phpenv installation directory, please replace with the actual path

**Comment by debo** [comment]
Oh wait, but this is a different thing you are doing. If I didn't misunderstand you, you want to add custom build options for a specific version different from the [default ones that come with php-build](https://github.com/php-build/php-build/blob/master/share/php-build/default_configure_options)

If you want to change the default build definition and pass different configuration options or install additional extensions you can use the enviers `PHP_BUILD_CONFIGURE_OPTS` and `PHP_BUILD_INSTALL_EXTENSION` you don't need to clone locally in order to have custom builds.

You can for example, in the case you presented you can do something like:

```shell
"PHP_BUILD_CONFIGURE_OPTS=--enable-gd --with-jpeg --with-zip --with-mhash --with-xmlrpc" phpenv install 8.1.3
```

**Comment by pgy866** [comment]
> 

Thanks a lot, this is a very good approach

**Comment by debo** [comment]
No problem at all
