### ISSUE TITLE
github.com/phpenv/phpenv  abandoned?

### ISSUE THREAD

**Issue by glensc** [phpenv/phpenv#57]
current state of "dev" branch does not work on initial setup, neither does "master" (looks like it expects php-src to be checked out manually because `cd php-src` is before `init()` call. etc)

last commit to "dev" branch is ~1y ago, commit to "master" branch ~2y ago
8 open pull requests, 15 open issues

is https://github.com/phpenv/phpenv  abandoned?

perhaps write to README.md what is this project and it's state and what is relation to the "other" project: https://github.com/CHH/phpenv

**Comment by gmorel** [comment]
:+1:

**Comment by sshymko** [comment]
+1

I wonder how can Travis CI use the project if it's in such a broken and abandoned state?

**Comment by augustohp** [comment]
> Or do they use CHH/phpenv?

Yes, As seen [in their doc](http://docs.travis-ci.com/user/languages/php/).

**Comment by outrunthewolf** [comment]
What a mess

**Comment by madumlao** [comment]
I'm a former contributor to phpenv and regular user of the upstream rbenv. I'm looking into whose fork is currently most active, but if I can't find anyone, I'm thinking of requesting to step up as the maintainer.

**Comment by bweston92** [comment]
@madumlao well I believe we need someone too.

**Comment by japboy** [comment]
:+1:

**Comment by tylercollier** [comment]
+1 to @madumlao

**Comment by madumlao** [comment]
I did my due diligence to send an email to CHH I think a couple months ago. I didn't get a reply and I'm not sure the email is still active.

I'm going to update my fork (https://github.com/madumlao/phpenv) to be buildable around the halloween season... should take me a few days, so would appreciate any help with the coffees and pizzas! (bountysource plug)

**Comment by bweston92** [comment]
@madumlao how can we trust you to maintain it for years :p

**Comment by madumlao** [comment]
@bweston92, I'm taking it one step at a time. my current concern is getting phpenv building again as I'm working on some php projects (whenever I make an API middleware, I do it in php).

As for maintaining it in the long term, my primary dev languages are ruby and php and I cannot live without rbenv. So I will always want an equivalent in other languages. Currently I am also a contributor in nenv (nodejs) and surprisingly jenv (java), which started from / are based on the same codebase. So this is one of my personal itches.

**Comment by tylercollier** [comment]
Alright @madumlao , I contributed to the bounty.

**Comment by madumlao** [comment]
I appreciate the gesture, @tylercollier  :)

**Comment by rogeriopradoj** [comment]
Hello, guys.

Always remember that "original ;-)" [phpenv, from CHH](https://github.com/CHH/phpenv), still working very well together with [php-build](https://github.com/php-build/php-build).

My current and working way of installing new php versions in my OS is with
https://github.com/php-build/php-build/wiki/phpenv-tools (`phpenv install`, `phpenv update` and `phpenv common deps install` are very life saver to me).

I think you could take a look there!

See ya!

**Comment by rogeriopradoj** [comment]
And I'm just kidding about original phpenv, ok? Please, no hard feelings ;-) .

As @augustohp told me once, the original in fact was created by @humandev, right?

**Comment by tylercollier** [comment]
This phpenv project is different from CHH's in 2 important ways, IMHO:

1. It's based on [rbenv](https://github.com/sstephenson/rbenv), which is a great stable project, that I am also familiar with.
2. It is much better documented. It even has instructions for working with Apache.

So no hard feelings here either, but I mention these things because I would love for others to join me in encouraging madumlao in taking over this project. You can do that with [this bountysource link](https://www.bountysource.com/issues/5756856-github-com-phpenv-phpenv-abandoned) and contributing some money!

**Comment by outrunthewolf** [comment]
:+1:

**Comment by rogeriopradoj** [comment]
:wink:

**Comment by madumlao** [comment]
Aight, thanks for the support! For a moment I thought you'd prefer to run the CHH version instead, but since this one has quite some love, I'll push on. Worry not, I'm still doing it even if we're under the target goal.

I'm running a few dev cycles this week to update phpenv to rbenv semantics and get it building. I'll update here as it gets finished.

**Comment by madumlao** [comment]
I looked over the php-build plugin (https://github.com/php-build/php-build) which is currently active, closer to upstream, and well-maintained. An initial test shows that it's trivial to remove the phpenv-specific php-install and delegate building to php-build.

My first maintenance commit (https://github.com/madumlao/phpenv/commit/9503cebe49336ea0cb126500995846844797d67a) removes php-install functionality from inside of php-build. I know this removes features, but on the other hand, it gets phpenv building again.

I'm going to look into the removed features and figure out ways of re-adding them, either using the plugin, a fork, or some convenience config within phpenv.

**Comment by madumlao** [comment]
So heads up, as of the moment, https://github.com/madumlao/phpenv is currently building (with help from https://github.com/php-build/php-build)

**Comment by rogeriopradoj** [comment]
@madumlao awesome! In fact I'm one of the contributors there (https://github.com/orgs/php-build/people).

Please, let us know if we can work better together, right?

And again, very cool!

**Comment by tylercollier** [comment]
Awesome, thanks @madumlao! I starred your repository.

**Comment by madumlao** [comment]
thanks!

@rogeriopradoj im going to review the install features added by phpenv and possibly make pull requests to php-build to add them in if missing.

possibly the biggest one users would look for is the way to specify custom compile options so you can add/disable php extensions, with the apache extension probably wanted most.

php-build #295 is probably related.

atm, phpenv will suggest the use of php-fpm instead of mod_php instead. docs have already been changed to reflect that.

**Comment by debo** [comment]
@madumlao first of all thanks a lot for your help and contribution to this amazing project. Just so you know I tried to reach @nickl- on Linkedin hoping he is going to pass the lead to you. He appears to not be that active on the various social channels so let's hope for the best.

**Comment by mfdj** [comment]
The [Github organization](https://github.com/phpenv) is owned by @humanshell — perhaps they can help transfer ownership to @madumlao or update the reamde.md to direct folks to the maintained fork. This repo has SEO visibility and quite a few github stars so I think it would be helpful to the community.

**Comment by debo** [comment]
Hi @mfdj I wish that was the case but unfortunately it's not like that. @humanshell is the only visible user and it's kind of honorary member, @nickl- is the actual owner. 
I reached him out and we both contacted GitHub to get to move this forward but following is the response we got:
> Organisations are designed so that repositories are not owned by one individual, each organisation typically has many owners so that - in your example - if one individual were to go AWOL, the project is not abandoned as there would be other owners with the necessary permissions to continue.
> 
> Unfortunately the phpenv organisation was not set up this way. Our user security policy is very strict on not making changes to user's accounts. This policy ensures that the work our users trust us with is protected but can also leave us in unpleasant situations such as this. I won't be able to change the ownership of the phpenv organisation or the repository, as much as I'd love to help here, as this is only something the existing owner can do.
> 
> I believe the best solution here would be to either pick the most active fork, or even create a new organisation - owned by several members of the community - and fork it there, and ask us to detach it. That would then start a new repository network and over time people would adjust their links to point to the right place.
> 
> I'm sorry I can't be more helpful here, as the core issue is granting someone access to another user's account - it's really not something we're able to compromise on.

And all this time along they have been adamant despite @humanshell even has his name in the phpenv's copyright. I am really disappointed with GitHub behaviour on this matter because, although I perfectly understand where they are coming from they shouldn't treat a case like this, which clearly requires some deeper human understanding (@nickl- has been offline from any known media for the past 3 years at least and yes I'm sorry I'm inferring something bad happened) and not the application of an "automatic" protocol/policy. Not even the fact I'm the phansible lead mainteiner seemed to be enough to give me trust.
In the meantime I did create the phpenv organisation on GitLab and I would be more than happy to collaborate with @madumlao and move the development over there if that could be a path we would like to pursue. In a way, so far, GitLab demonstrated to be way more opensource friendly than GitHub. @humanshell in the meantime suggested to create a new org project called **phpem**: The **PHP** **E**nvironment **M**anager. Thoughts?

**Comment by tylercollier** [comment]
If @madumlao continues with his fork, that should eventually be enough. This happens from time to time. It happened with ryanb, the guy from Railscasts, who was I believe how I got into rbenv (and what this version of phpenv is based on). Ryan created the [cancan](https://github.com/ryanb/cancan) project, then abandoned it, and eventually [cancancan](https://github.com/CanCanCommunity/cancancan) got enough steam that it's the new home. It's totally a bummer that it has to work this way, but I want @madumlao to be encouraged that his time and effort will be worth it: eventually people will know to use his fork.

It would be more work, but if he or someone monitors this repo for issues and explains the situation and encourages issue posters to post their issue on the new fork, people will see the pattern on this repo's issues list.

**Comment by debo** [comment]
@tylercollier indeed the annoying bit is that we can't even redirect from here to @madumlao's fork so at least people know where to go for things and spread the voice around. 
I'm thankful for his work and I hope he doesn't give up.

**Comment by madumlao** [comment]
Guys, thanks so so much for your support and understanding.

I intend to keep my fork going on for as long as I'm using php, and I am using it relatively a lot as I'm currently using Laravel for some on the side work. I may not be as active as I would like (frankly, rbenv was written so well there's not that much to do!) but php is not going away from my life, at least not within the next decade.

For your support I'll just request that you redirect any issues from here to my fork. I will also be eyeing getting a domain name for phpenv that will help explain the situation although [updating my blog](http://madumlao.is-a-geek.org) (which I've not done in years) is on the very bottom of my priorities.

All this needs to be "official" is for that phpenv website - maybe run by you fine folks - to be the top google search explaining the situation.

Again thanks for the support and I really hope @nickl is doing alright. Frankly I did get worried as his online presence dropped off the planet.

**Comment by humanshell** [comment]
All,

As @debo explained above, he and I corresponded with Github Support in an attempt to alter the admin/ownership of this org without success. I too am disappointed in Github, although I have to admit that their adherence to repo and org security is comforting.

I started [my](https://github.com/humanshell/phpenv) original project while working on a large WordPress site for a university. I needed a way to more easily confirm plugin development on multiple PHP versions. When I left PHP to take up Ruby, @nickl- took over and created this org. I am happy that so many other Open Source users continue to benefit from and enjoy using something that I created.

As I am only a Member of this org I'm not sure if I can even `push` code changes - but I am more than happy to try. I can attempt to edit the README to direct current and future users to @madumlao's fork and/or to the new GitLab project. But I would like to hear from all of you; please let me know here how you would like the README edited and what you would like it to say.

I will help in any way I can so that all of you can move the development and growth of this tool forward in the way you see fit.

humanshell

**Comment by tonglil** [comment]
@humanshell as you are the only member of this org, you can ask @github to make you an admin, and then you should make someone (hopefully multiple) people admins so active people can move forward with this tool and namespace.

**Comment by debo** [comment]
@tonglil as we expained we already tried, but sadly @humanshell is only a member and the fact that his name is clearly declared in the copyright credits of the project didn't move GitHub customer suppose a single inch. Unfortunately @nickl- is the only owner and we are stuck with it.

There are two things we can do, one is to try to make @madumlao repo popular advertising it on all the possible channels or, assuming that @madumlao is ok with it, move the phpenv over to a more friendly tool such as gitlab. In the latter case I already reserved the phpenv organisation just in case.

**Comment by debo** [comment]
Hey @nickl- welcome back! We missed you, I hope everything is fine with you? I would love to help keep the project going, I think that if you could add Dominic and me as owner/admin to the org that would be bliss.

**Comment by nickl-** [comment]
Done! and gl!

**Comment by madumlao** [comment]
Hi nick, as im effectively the active maintainer atm, could you  grant me access?

**Comment by debo** [comment]
To you too buddy, and thanks for having it made this far for the project it helped me and many other people a lot. All the best to you.

**Comment by nickl-** [comment]
I did have a look at some point at what I still had outstanding but it wasn't worth submitting. So all yours, shout if you need anything else.

**Comment by nickl-** [comment]
@madumlao you should also have an invite...

**Comment by nickl-** [comment]
@debo np... look forward to see what you've done =)

**Comment by nickl-** [comment]
@madumlao sorted?

**Comment by madumlao** [comment]
Fantastic guys, tbh i wasnt sure we were going to get to close this bug.

btw, does anyone know who owns the phpenv.org domain if its still running?

**Comment by madumlao** [comment]
@nickl- all is in order with github and once again thanks for all the help :)

**Comment by debo** [comment]
The domain seems down but I'm happy to sponsor it if needed.

**Comment by madumlao** [comment]
If no one has objections, I'll close this bug as soon as master is updated with my fork.

**Comment by nickl-** [comment]
@madumlao the owner of the domain committed to keep it up and it should be pointing to gh-pages branch on he phpenv.org project so you have full access.

**Comment by nickl-** [comment]
+1 on closing

**Comment by debo** [comment]
+1 on closing

**Comment by nickl-** [comment]
gl guys! have phun!

**Comment by madumlao** [comment]
@debo that would be great. hopefully some evil domain squatter hasn't sniped it yet.

**Comment by debo** [comment]
Thanks @nickl- all the best to you too.

**Comment by debo** [comment]
@madumlao both phpenv.org and phpenv.io seems free, which one would you prefer? I prefer the latter but I'm easy.

**Comment by madumlao** [comment]
@debo, .org is referenced by the organization so i would assume thats for the better.

**Comment by debo** [comment]
@madumlao up to us as I said, we can always change it. I'll go with org for now, it's also probably cheaper :-)

**Comment by nickl-** [comment]
gh pages:  https://pages.github.com
custom urls: https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by madumlao** [comment]
Guys, #85 has been merged, effectively putting phpenv up-to-date!

In addition, I've added phpenv-installer to the phpenv org to make getting an up-to-date phpenv easier for new and older users! I'll be closing this issue soon if there are no major issues

**Comment by madumlao** [comment]
Okay, I've had a pass at most of the issues in the issue tracker. Pretty much everything was related to phpenv being out of date, so I've had to close most of them. Some issues / questions are still relevant and I've left them open.

S here's a call for any complaints on the latest production phpenv before I can consider this closed. Please raise any issues discovered with the latest set of updates in this thread before I can consider it shipped.

It's also been a loong time since this has been updated, and I now realize that there has been some money sitting on the bountysource tracker (https://www.bountysource.com/issues/5756856-github-com-phpenv-phpenv-abandoned) that was put in waaay back for my fork, but hasn't been claimed (as technically the issue hasn't closed). I've pledged @debo the amount for keeping the domain up, but just in case anyone wants to buy me a pizza or two for the effort, please check out the bountysource tracker here: https://www.bountysource.com/issues/5756856-github-com-phpenv-phpenv-abandoned

I'll look into setting up something on Patreon and/or bountysource or other channels to support future development if there's more love to be had.

**Comment by debo** [comment]
@madumlao great work man, keep the spam coming, and if you need any help with some of the tickets please shout and I'll help.
