### ISSUE TITLE
pass parameters for ./configure

### ISSUE THREAD

**Issue by cabelotaina** [phpenv/phpenv#66]
Hi all,

A need pass a parater for ./configure on phpenv install <new_php>

Exist someone solution for this?

This is the parameter:

./configure --with-pdo-pgsql

tks

**Comment by madumlao** [comment]
Hi @cabelotaina . Sorry for the extreeemely late reply. We've had org issues as in #57 :)

Configure options can be set in the environment variable `PHP_BUILD_CONFIGURE_OPTS` prior to running phpenv install.

~~~
export PHP_BUILD_CONFIGURE_OPTS="--enable-foo"
phpenv install
~~~

should add `--enable-foo` in the configure opts.

See the php-build man page for reference:
https://github.com/php-build/php-build/blob/master/man/php-build.1.ronn

Personally, I have it defined in my `~/.profile`, so that all future installations of php are consistent.

~~~
export PHP_BUILD_CONFIGURE_OPTS="--with-ldap=/usr --with-mcrypt=/usr --with-mhash=/usr --with-mysql-sock=/run/mysqld/mysqld.sock"
~~~
