### ISSUE TITLE
Automatically switch PHP on per-directory .php-version file

### ISSUE THREAD

**Issue by mcandre** [phpenv/phpenv#68]
Does phpenv support automatically applying the right version of PHP based on per-directory `.php-version` files, the way chruby, pyenv, jenv.io do this for Ruby, Python, and Java projects?

If not, could this feature please be added? Does anyone know of another PHP environment switcher that does offer this feature?

**Comment by ShaneGlee** [comment]
You can use php-version with phpenv by setting up the versions directory as part of your bash profile.

`export PHP_VERSIONS="$HOME/.phpenv/versions"`

**Comment by madumlao** [comment]
Sorry for the extreme late reply @mcandre. We've had org issues as in #57.

phpenv can and will automatically switch php versions based on the contents of `./.phpenv-version` and/or inputs to `phpenv local`.

CAVEAT:
If PHP is started using `php-fpm` or the apache module, phpenv itself cannot perform per-directory switching. That would have to be done at the webserver level.

---
Supported
~~~
~ $ phpenv version
5.5.38 (set by /home/madumlao/.phpenv/version)
~ $ cd Projects/foo
~/Projects/foo $ phpenv version
7.0.4 (set by /home/madumlao/Projects/foo/.php-version)
~/Projects/foo $ phpenv local 7.2.1
7.2.1
~/Projects/foo $ phpenv version
7.2.1 (set by /home/madumlao/Projects/foo/.php-version)
~/Projects/foo $ rm .php-version
~/Projects/foo $ phpenv version
5.5.38 (set by /home/madumlao/.phpenv/version)
~~~

---

Unsupported

 - set phpenv version in `~/public_html/foo` as 5.5.38
 - set phpenv version in `~/public_html/foo/bar` as 7.2.1
 - visit `http://localhost/foo/info.php` and see 5.5.38 as version
 - visit `http://localhost/foo/bar/info.php` and see 7.2.1 as version

The supported way to do the above is:

 - start / run php-fpm using PHP 5.5.38 with `~/run/php-5.5.38.sock`
 - start / run php-fpm using PHP 7.2.1 with `~/run/php-7.2.1.sock`
 - setup your Apache / nginx so that Location = /foo uses FastCGI with `~/run/php-5.5.38.sock`
 - setup your Apache / nginx so that Location = /foo/bar uses FastCGI with `~/run/php-7.2.1.sock`
