### ISSUE TITLE
Feature request: add user and group env to systemd (init.d) config

### ISSUE THREAD

**Issue by mrPsycho** [phpenv/phpenv#94]
hello,

it is cool that now it generates simple systemd config. 
so my FR is to add something like this: 
```
User=$username
Group=$usergroup
```

to `[Service]` section in `php-fpm.service`.

it is not a problem to add it by myself... but would be cool to limit it on installation step.

ps. and same with php-fpm.conf - cause default user is www... and it is not relevant.

**Comment by madumlao** [comment]
Hi,
Again apologies for the inactivity. Recently had local projects take up time.

The systemd config isn't generated, but rather just copied from the upstream PHP systemd config. Since the upstream systemd unit works as-is, I would rather avoid having phpenv make changes to it. It might be within scope for a plugin though.

If this is for a local development instance, one way to run the systemd unit inside a user slice, for example:

~~~
cp $(phpenv prefix)/etc/systemd/system/php-fpm.service $HOME/.config/systemd/user/
systemctl --user start php-fpm
systemctl --user enable php-fpm
~~~

The php-fpm service will automatically start on user login.
