### ISSUE TITLE
phpenv + 7.2 + modules

### ISSUE THREAD

**Issue by mrPsycho** [phpenv/phpenv#95]
Hello,

i don't know where to ask... cause there is no info about google groups or something like that. 

but. 

i've installed 7.2.12 with phpenv - and plain php works fine. 
now i want to add modules, like ldap, mcrypt and some others... how i can do that? 

i've installed `pear` - but it doesn't contain needed modules. 
next i tried to install `pyrus`.  
to work - it is needed to run like that `php /home/phpenv/.phpenv/versions/7.2.12/bin/pyrus.phar`... this is ok, but when i'v trying to install `mcrypt`:
```
# php /home/phpenv/.phpenv/versions/7.2.12/bin/pyrus.phar install https://pecl.php.net/get/mcrypt-1.0.1.tgz
Pyrus version 2.0.0a4 SHA-1: 72271D92C3AA1FA96DF9606CD538868544609A52
Using PEAR installation found at /home/phpenv/.pyrus
Mime-type: application/octet-stream
Pyrus\Package\Exception: Could not download from "https://pecl.php.net/get/mcrypt-1.0.1.tgz"=========>] 100% (32/32 kb)
 Pyrus\PackageFile\Exception: Invalid package.xml
  Pyrus\XMLParser\Exception: Invalid XML document
   Pyrus\XMLParser\Exception: Line 137: Element '{http://pear.php.net/dtd/package-2.0}notes': This element is not expected. Expected is ( {http://pear.php.net/dtd/package-2.0}stability ).
```

how i can install these modules?

**Comment by mrPsycho** [comment]
ok. 
i figured something.

i managed to install `pecl`... it doesn't update `php.ini`, but it does most of the task, so fine. 
also `pear` works that exist on `pear.php.net`, it is cool to.

but, i have question - how to rebuild php with next modules:
ldap
imap
ftp 
exif
gmp
pcntl
?

**Comment by mrPsycho** [comment]
looks to me i find solution:

`PHP_BUILD_CONFIGURE_OPTS=--with-curl --with-ldap --with-imap --with-gd phpenv install -f 7.2.12`

**Comment by guangrei** [comment]
sound interesting, i usually install the extension with phpize > ./configure > make > make install

**Comment by mrPsycho** [comment]
@guangrei it didn't worked for curl and ftp, for example. 

or, i don't know to use it with built-in-source modules.

**Comment by guangrei** [comment]
I have tried installing gmp extension from php source https://github.com/php/php-src/tree/master/ext, and it's work with phpize > ./configure > make > make install

**Comment by madumlao** [comment]
Apologies guys, haven't been active recently due to local projects.

> i've installed pear - but it doesn't contain needed modules.
> next i tried to install pyrus.

It isn't exactly clear how you attempted to install pear / pecl / pyrus. Typically you want to install these as _part_ of your php build, by adding the appropriate build option (`--with-pear`) below. Upon doing so, the pear executable should be installed in your PHP prefix, allowing you to `pear install` | `pecl install` and have the resulting package installed in your prefix.

> looks to me i find solution:
> 
> `PHP_BUILD_CONFIGURE_OPTS=--with-curl --with-ldap --with-imap --with-gd phpenv install -f 7.2.12`

Yes, this is the official way to add modules to a phpenv build. Personally, I put that in my profile so that all my PHP builds get the above options. Just note that you will occasionally run into build troubles if the current PHP version has a library issue or your OS doesn't have the development headers for the above.

**Comment by madumlao** [comment]
[PR#108](https://github.com/phpenv/phpenv/pull/108) documents how options are added to php-build.
